# The Relation to Text dict 
nyt_rel2text = {
                '/business/company/advisors': 'advisors',
                '/business/company/founders': 'founders',
                '/business/company/industry': 'industry',
                '/business/company/major_shareholders': 'holding',
                '/business/company/place_founded': 'founded',
                '/business/company_shareholder/major_shareholder_of':
                'shareholder',
                '/business/person/company': 'company',
                '/location/administrative_division/country': 'country',
                '/location/country/administrative_divisions': 'administrative',
                '/location/country/capital': 'capital',
                '/location/location/contains': 'contains',
                '/location/neighborhood/neighborhood_of': 'neighbor',
                '/people/deceased_person/place_of_death': 'death',
                '/people/ethnicity/geographic_distribution': 'geographic',
                '/people/ethnicity/people': 'people',
                '/people/person/children': 'children',
                '/people/person/ethnicity': 'ethnicity',
                '/people/person/nationality': 'nationality',
                '/people/person/place_lived': 'lived',
                '/people/person/place_of_birth': 'birthplace',
                '/people/person/profession': 'profession',
                '/people/person/religion': 'religion',
                '/sports/sports_team/location': 'location',
                '/sports/sports_team_location/teams': 'teams'
            }

nyt_rel2text_ablation = {
                # '/business/company/advisors': 'adviser',
                '/business/company/advisors': 'counselor',
                '/business/company/founders': 'creator',
                '/business/company/industry': 'sector',
                '/business/company/major_shareholders': 'shareholder',
                '/business/company/place_founded': 'establish',
                '/business/company_shareholder/major_shareholder_of':
                'holder',
                '/business/person/company': 'corporation',
                '/location/administrative_division/country': 'state',
                '/location/country/administrative_divisions': 'administration',
                '/location/country/capital': 'Capital',
                '/location/location/contains': 'include',
                '/location/neighborhood/neighborhood_of': 'neighbour',
                '/people/deceased_person/place_of_death': 'Death',
                '/people/ethnicity/geographic_distribution': 'Geographic',
                '/people/ethnicity/people': 'People',
                '/people/person/children': 'Children',
                '/people/person/ethnicity': 'ethnic',
                '/people/person/nationality': 'national',
                '/people/person/place_lived': 'live',
                '/people/person/place_of_birth': 'birth',
                '/people/person/profession': 'career',
                '/people/person/religion': 'Religion',
                '/sports/sports_team/location': 'Location',
                '/sports/sports_team_location/teams': 'Teams'
            }

webnlg_rel2text = {
    "1st_runway_LengthFeet": 1,
    "1st_runway_LengthMetre": 2,
    "1st_runway_Number": 3,
    "1st_runway_SurfaceType": 4,
    "2nd_runway_SurfaceType": 5,
    "3rd_runway_LengthFeet": 6,
    "3rd_runway_SurfaceType": 7,
    "4th_runway_LengthFeet": 8,
    "5th_runway_Number": 9,
    "CODEN_code": 10,
    "EISSN_number": 11,
    "IATA_Location_Identifier": "IATA",
    "ICAO_Location_Identifier": "ICAO",
    "ISBN_number": "ISBN",
    "ISSN_number": "ISSN",
    "LCCN_number": 12,
    "LibraryofCongressClassification": 13,
    "OCLC_number": "OCLC",
    "ReferenceNumber in the National Register of Historic Places": 14,
    "abbreviation": "abbreviation",
    "academicDiscipline": "discipline",
    "academicStaffSize": "staff",
    "added to the National Register of Historic Places": "historic",
    "address": "address",
    "administrativeArrondissement": "arrondissement",
    "administrativeCounty": "administrative",
    "affiliation": "affiliation",
    "affiliations": "affiliate",
    "aircraftFighter": "fighter",
    "aircraftHelicopter": "helicopter",
    "almaMater": "alma",
    "alternativeName": "alternative",
    "anthem": "anthem",
    "architect": "architect",
    "architecturalStyle": "style",
    "architecture": "architecture",
    "areaCode": "area",
    "areaOfLand": "land",
    "areaOfWater": "water",
    "areaTotal": "areas",
    "attackAircraft": "attack",
    "author": "author",
    "award": "award",
    "awards": "awards",
    "backup pilot": "pilot",
    "battles": "battle",
    "bedCount": "beds",
    "bird": "bird",
    "birthName": "surname",
    "birthPlace": "birthplace",
    "broadcastedBy": "broadcast",
    "buildingStartDate": "builds",
    "buildingType": "Building",
    "campus": "campus",
    "capital": "capital",
    "category": "category",
    "chairman": "chairman",
    "chairmanTitle": "Chairman",
    "chairperson": "chair",
    "champions": "champion",
    "chancellor": "chancellor",
    "chief": "chief",
    "child": "child",
    "city": "city",
    "cityServed": "served",
    "class": "class",
    "club": "club",
    "commander": "commander",
    "compete in": "compete",
    "completionDate": "completion",
    "country": "country",
    # "country": "nation",
    "countySeat": "seat",
    "course": "course",
    "creator": "creator",
    "creatorOfDish": "dishes",
    "crewMembers": "crews",
    "currency": "currency",
    "currentTenants": "tenants",
    "dean": "dean",
    "deathPlace": "death",
    "dedicatedTo": "dedicated",
    "demonym": "evil",
    "designer": "designer",
    "developer": "developer",
    "director": "director",
    "dishVariation": "dish",
    "distributor": "distributor",
    "district": "district",
    "division": "division",
    "doctoralAdvisor": "advisor",
    "editor": "editor",
    "elevationAboveTheSeaLevel": "above",
    "elevationAboveTheSeaLevel_(in_feet)": "feet",
    "elevationAboveTheSeaLevel_(in_metres)": "metre",
    "established": "establish",
    # "ethnicGroup": "group",
    "ethnicGroup": "ethnic",
    "ethnicGroups": "Ethnic",
    "family": "family",
    "fat": "fat",
    "firstAppearanceInFilm": "film",
    "firstPublicationYear": "publication",
    "floorArea": "floor",
    "floorCount": "floors",
    "followedBy": "follow",
    "fossil": "fossil",
    "foundationPlace": "founded",
    "foundedBy": "Founder",
    "founder": "founder",
    "fullName": "name",
    "fullname": "Name",
    "gemstone": "cameo",
    "genre": "Style",
    "literaryGenre":"genre",
    "genus": "genus",
    "governingBody": "governing",
    "governmentType": "government",
    "ground": "ground",
    "has to its north": "north",
    "has to its northeast": "northeast",
    "has to its northwest": "northwest",
    "has to its southeast": "southeast",
    "has to its southwest": "southwest",
    "has to its west": "west",
    "headquarter": "quarter",
    "headquarters": "quarters",
    "height": "height",
    "higher": "higher",
    "hometown": "hometown",
    "hubAirport": "airport",
    "inaugurationDate": "inauguration",
    "influencedBy": "influenced",
    # "ingredient": "component",
    "ingredient": "ingredient",
    "isPartOf": "part",
    "jurisdiction": "jurisdiction",
    "keyPerson": "key",
    "language": "language",
    "languages": "languages",
    "largestCity": "largest",
    "latinName": "Latin",
    "leader": "lead",
    "leaderName": "leader",
    "leaderParty": "party",
    "leaderTitle": "boss",
    "league": "league",
    "legislature": "legislature",
    "location": "location",
    "locationCity": "locate",
    "mainIngredients": "ingredients",
    "manager": "manager",
    "material": "material",
    "mayor": "mayor",
    "mediaType": "media",
    "motto": "motto",
    "municipality": "municipality",
    "nationality": "nationality",
    "nativeName": "native",
    "nearestCity": "nearest",
    "neighboringMunicipality": "neighbor",
    "nickname": "nickname",
    "notableWork": "work",
    "numberOfMembers": "members",
    "numberOfPages": "pages",
    "numberOfPostgraduateStudents": "postgraduate",
    "numberOfRooms": "room",
    "numberOfStudents": "students",
    "numberOfUndergraduateStudents": "undergraduate",
    "occupation": "occupation",
    "officialLanguage": "Language",
    "officialSchoolColour": "colour",
    "operatingOrganisation": "operating",
    "operator": "operator",
    "order": "order",
    "outlookRanking": "ranking",
    "owner": "owner",
    "owningOrganisation": "owning",
    "parentCompany": "company",
    "part": "Part",
    "partsType":"parts",
    "patronSaint": "patron",
    "placeOfBirth": 15,
    "placeOfDeath": 16,
    "populationDensity": "density",
    "populationTotal": "population",
    "postalCode": "postal",
    "precededBy": "preceded",
    "president": "president",
    "product": "product",
    "protein": "protein",
    "publisher": "publisher",
    "rector": "rector",
    "region": "region",
    "regionServed": "Region",
    "religion": "religion",
    "representative": "representative",
    "residence": "residence",
    "river": "river",
    "runwayLength": "length",
    "runwayName": "runway",
    "season": "season",
    "senators": "senator",
    "series": "series",
    "served as Chief of the Astronaut Office in": "astronaut",
    "servingTemperature": "temperature",
    "significantBuilding": "building",
    "significantProject": "project",
    "spokenIn": "spoken",
    "sportsGoverningBody": "sport",
    "sportsOffered": "sports",
    "starring": "starring",
    "state": "state",
    "tenant": "tenant",
    "title": "title",
    "transportAircraft": "transport",
    "voice": "voice",
    "was a crew member of": "crew",
    "was given the 'Technical Campus' status by": "technical",
    "was selected by NASA": "NASA",
    "year": "year",
    "yearOfConstruction": "construction",
    "youthclub": "youth" 
}

webnlg_rel2clearrep = {
    "1st_runway_LengthFeet": "first feet",
    "1st_runway_LengthMetre": "first metre",
    "1st_runway_Number": "first number",
    "1st_runway_SurfaceType": "firset surface",
    "2nd_runway_SurfaceType": "second surface",
    "3rd_runway_LengthFeet": "third feet",
    "3rd_runway_SurfaceType": "third surface",
    "4th_runway_LengthFeet": "forth feet",
    "5th_runway_Number": "fivth number",
    "CODEN_code": "CODEN",
    "EISSN_number": "EISSN",
    "IATA_Location_Identifier": "IATA",
    "ICAO_Location_Identifier": "ICAO",
    "ISBN_number": "ISBN",
    "ISSN_number": "ISSN",
    "LCCN_number": "LCCN",
    "LibraryofCongressClassification": "LCC",
    "OCLC_number": "OCLC",
    "ReferenceNumber in the National Register of Historic Places": "reference NRHP",
    "abbreviation": "abbreviation",
    "academicDiscipline": "academicDiscipline",
    "academicStaffSize": "academicStaffSize",
    "added to the National Register of Historic Places": "add NRHP",
    "address": "address",
    "administrativeArrondissement": "administrativeArrondissement",
    "administrativeCounty": "administrativeCounty",
    "affiliation": "affiliation",
    "affiliations": "affiliate",
    "aircraftFighter": "aircraftFighter",
    "aircraftHelicopter": "aircraftHelicopter",
    "almaMater": "almaMater",
    "alternativeName": "alternativeName",
    "anthem": "anthem",
    "architect": "architect",
    "architecturalStyle": "architecturalStyle",
    "architecture": "architecture",
    "areaCode": "area",
    "areaOfLand": "areaOfLand",
    "areaOfWater": "areaOfWater",
    "areaTotal": "areaTotal",
    "attackAircraft": "attackAircraft",
    "author": "author",
    "award": "award",
    "awards": "awards",
    "backup pilot": "backup pilot",
    "battles": "battle",
    "bedCount": "bedCount",
    "bird": "bird",
    "birthName": "surname",
    "birthPlace": "birthplace",
    "broadcastedBy": "broadcast",
    "buildingStartDate": "builds",
    "buildingType": "Building",
    "campus": "campus",
    "capital": "capital",
    "category": "category",
    "chairman": "chairman",
    "chairmanTitle": "chairmanTitle",
    "chairperson": "chairperson",
    "champions": "champion",
    "chancellor": "chancellor",
    "chief": "chief",
    "child": "child",
    "city": "city",
    "cityServed": "cityServed",
    "class": "class",
    "club": "club",
    "commander": "commander",
    "compete in": "compete",
    "completionDate": "completionDate",
    "country": "country",
    # "country": "nation",
    "countySeat": "countySeat",
    "course": "course",
    "creator": "creator",
    "creatorOfDish": "creatorOfDish",
    "crewMembers": "crewMembers",
    "currency": "currency",
    "currentTenants": "currentTenants",
    "dean": "dean",
    "deathPlace": "deathPlace",
    "dedicatedTo": "dedicated",
    "demonym": "evil",
    "designer": "designer",
    "developer": "developer",
    "director": "director",
    "dishVariation": "dish",
    "distributor": "distributor",
    "district": "district",
    "division": "division",
    "doctoralAdvisor": "doctoralAdvisor",
    "editor": "editor",
    "elevationAboveTheSeaLevel": "above sea level",
    "elevationAboveTheSeaLevel_(in_feet)": "feet above sea level",
    "elevationAboveTheSeaLevel_(in_metres)": "metre above sea levle",
    "established": "establish",
    # "ethnicGroup": "group",
    "ethnicGroup": "ethnic group",
    "ethnicGroups": "ethnic groups",
    "family": "family",
    "fat": "fat",
    "firstAppearanceInFilm": "appearance film",
    "firstPublicationYear": "publication year",
    "floorArea": "floor",
    "floorCount": "floors",
    "followedBy": "follow",
    "fossil": "fossil",
    "foundationPlace": "foundation",
    "foundedBy": "founded",
    "founder": "founder",
    "fullName": "Name",
    "fullname": "name",
    "gemstone": "cameo",
    "genre": "genre",
    "literaryGenre":"literaryGenre",
    "genus": "genus",
    "governingBody": "governing",
    "governmentType": "government",
    "ground": "ground",
    "has to its north": "north",
    "has to its northeast": "northeast",
    "has to its northwest": "northwest",
    "has to its southeast": "southeast",
    "has to its southwest": "southwest",
    "has to its west": "west",
    "headquarter": "quarter",
    "headquarters": "quarters",
    "height": "height",
    "higher": "higher",
    "hometown": "hometown",
    "hubAirport": "airport",
    "inaugurationDate": "inauguration",
    "influencedBy": "influenced",
    # "ingredient": "component",
    "ingredient": "ingredient",
    "isPartOf": "part of",
    "jurisdiction": "jurisdiction",
    "keyPerson": "key person",
    "language": "language",
    "languages": "languages",
    "largestCity": "largest city",
    "latinName": "latin name",
    "leader": "lead",
    "leaderName": "leader",
    "leaderParty": "leader party",
    "leaderTitle": "leader title",
    "league": "league",
    "legislature": "legislature",
    "location": "location",
    "locationCity": "locate",
    "mainIngredients": "main ingredient",
    "manager": "manager",
    "material": "material",
    "mayor": "mayor",
    "mediaType": "media type",
    "motto": "motto",
    "municipality": "municipality",
    "nationality": "nationality",
    "nativeName": "native",
    "nearestCity": "nearest",
    "neighboringMunicipality": "neighbor",
    "nickname": "nickname",
    "notableWork": "work",
    "numberOfMembers": "members",
    "numberOfPages": "pages number",
    "numberOfPostgraduateStudents": "postgraduate number",
    "numberOfRooms": "room number",
    "numberOfStudents": "students number",
    "numberOfUndergraduateStudents": "undergraduate number",
    "occupation": "occupation",
    "officialLanguage": "offical language",
    "officialSchoolColour": "offical colour",
    "operatingOrganisation": "operatingOrganisation",
    "operator": "operator",
    "order": "order",
    "outlookRanking": "ranking",
    "owner": "owner",
    "owningOrganisation": "owning",
    "parentCompany": "company",
    "part": "part",
    "partsType":"part type",
    "patronSaint": "patron",
    "placeOfBirth": "placeOfBirth",
    "placeOfDeath": "placeOfDeath",
    "populationDensity": "density",
    "populationTotal": "population number",
    "postalCode": "postal",
    "precededBy": "preceded",
    "president": "president",
    "product": "product",
    "protein": "protein",
    "publisher": "publisher",
    "rector": "rector",
    "region": "region",
    "regionServed": "Region",
    "religion": "religion",
    "representative": "representative",
    "residence": "residence",
    "river": "river",
    "runwayLength": "length",
    "runwayName": "runway",
    "season": "season",
    "senators": "senator",
    "series": "series",
    "served as Chief of the Astronaut Office in": "chief astronaut",
    "servingTemperature": "temperature",
    "significantBuilding": "significant building",
    "significantProject": "significant project",
    "spokenIn": "spoken",
    "sportsGoverningBody": "sport govern",
    "sportsOffered": "sports offer",
    "starring": "starring",
    "state": "state",
    "tenant": "tenant",
    "title": "title",
    "transportAircraft": "transport aircraft",
    "voice": "voice",
    "was a crew member of": "crew member",
    "was given the 'Technical Campus' status by": "technical campus",
    "was selected by NASA": "NASA",
    "year": "year",
    "yearOfConstruction": "construction year",
    "youthclub": "youth club" 
}